import os

SPEED_SLOW_MBPS = 10.0
SPEED_FAST_MBPS = 50.0
PAGE_SIZE = 5
VENUE_DEDUPE_RADIUS_M = 50
RATE_LIMIT_HOURS = 1
MAX_NEARBY_RADIUS_M = 100
ADMIN_USERNAME = os.environ.get("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "changeme")
